language: ruby
rvm:
  - 2.2.1
env:
  matrix:
    - DB=postgresql
  global:
    - secure: S6w3zf5pAexmTCUP7xOajo1cp8KiUjR8gNDrs9tZhPs1/B+ruE3gTM0zWTRfDw0oq0Sd8iKwr1bQEyZ/2AW1MPh+BF/M2pDWmj0PLgPeY/dV5nyrUngZlNf4ip3+ABJaas/aVHsvN7aqS4b1Bfzg4zdxbT1mNWXBergb1xQWLXPOrI3Zidy9p9yg57ApQFUOlP8IviDxl9VKmMURT4mqdlPV1t/Y+mTOEZREdzlqW0GGJOmSxlGZJtMw7VCXcrSaE5FK8F9NDSx33fRSfMgjRC8ylDWqwE+4PBWubxJfBs/g+pRKNH/Z9j1Ngp/m6t6TyhOQ8M1ZV0+xyEEyCJY9jqk9YCu2t3/15+/OrySY79tAyCEsRsVae18oKDQcFDVo6jXP+VucspdCsADb2jPiLiNgx2MVbh5xO2TIS3LSrCKRHAcsFrF5tPykpJywASRDUJlU9GbeIYJAofAacAAUtX869dbpSNBV7HU2LB4/lQG9shGSnti5BBdxlpwAm+WOGHfd26zUIu0OyIaPCdof4fC0rxYMOWb1LcWTPwaTf7kVOqjfzVK5u3rdIA9E6gWsB5mWmGG3yBKe62/8cuQWhD/JFVmv7u96KVK4zLduzYLJBtjAkpR1OA0R38+TnHaeRMFO4wisbUqU8j8ixIFIm5c5RkiIBDT7SMSxJHjEiOY=
before_install:
  - cp config/database.travis.yml config/database.yml
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec

addons:
  code_climate:
    repo_token: e6ef8bd1ffdfcb9fb4a39602638d8a45965c82207aef853775b348f4ca677694
