development:
  adapter: postgresql
  encoding: unicode
  database: programertv_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: programertv_test
  pool: 5
  username:
  password:
